CREATE TABLE "gpt_idea_likes" (
	"gpt_idea_id" bigint NOT NULL,
	"profile_id" uuid NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "gpt_idea_likes_gpt_idea_id_profile_id_pk" PRIMARY KEY("gpt_idea_id","profile_id")
);
--> statement-breakpoint
CREATE TABLE "gpt_ideas" (
	"gpt_idea_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gpt_ideas_gpt_idea_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"description" text NOT NULL,
	"views" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"claimed_at" timestamp,
	"claimed_by" uuid
);
--> statement-breakpoint
ALTER TABLE "gpt_idea_likes" ADD CONSTRAINT "gpt_idea_likes_gpt_idea_id_gpt_ideas_gpt_idea_id_fk" FOREIGN KEY ("gpt_idea_id") REFERENCES "public"."gpt_ideas"("gpt_idea_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gpt_idea_likes" ADD CONSTRAINT "gpt_idea_likes_profile_id_profiles_profile_id_fk" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("profile_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gpt_ideas" ADD CONSTRAINT "gpt_ideas_claimed_by_profiles_profile_id_fk" FOREIGN KEY ("claimed_by") REFERENCES "public"."profiles"("profile_id") ON DELETE cascade ON UPDATE no action;