CREATE TYPE "public"."product_stages" AS ENUM('Idea', 'MVP', 'Beta', 'Launched', 'Scaling');--> statement-breakpoint
CREATE TABLE "teams" (
	"team_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "teams_team_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"product_name" text NOT NULL,
	"product_stage" "product_stages" NOT NULL,
	"team_size" integer NOT NULL,
	"equity_split" integer NOT NULL,
	"roles" text NOT NULL,
	"description" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "equity_split" CHECK ("teams"."equity_split" >= 0 AND "teams"."equity_split" <= 100),
	CONSTRAINT "team_size" CHECK ("teams"."team_size" >= 1 AND "teams"."team_size" <= 100),
	CONSTRAINT "product_description_check" CHECK (LENGTH("teams"."description") > 0 AND LENGTH("teams"."description") <= 200)
);
--> statement-breakpoint
ALTER TABLE "jobs" ADD COLUMN "location" "location_type" NOT NULL;--> statement-breakpoint
ALTER TABLE "jobs" DROP COLUMN "location_type";